# Generated by Django 5.2.4 on 2025-08-12 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('donation', 'Donation')], max_length=10)),
                ('price_per_day', models.FloatField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_to', models.DateTimeField(blank=True, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
