# Generated by Django 5.2.4 on 2025-08-12 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_id_number', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('license', 'License'), ('passport', 'Passport'), ('national_id', 'National ID'), ('voter_id', 'Voter ID'), ('pan_card', 'PAN Card'), ('aadhaar', 'Aadhaar'), ('other', 'Other')], max_length=20)),
                ('document_front_picture', models.TextField()),
                ('document_back_picture', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=15)),
                ('temp_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
                'unique_together': {('gov_id_number', 'document_type')},
            },
        ),
    ]
